### ISSUE TITLE
Unactive chrome window + tab bug 

### ISSUE THREAD

**Issue by yoyurec** [bramstein/fontfaceobserver#1]
On chrome ubuntu v.41 (Firefox is OK) + Chrome 40 (win):
* open **any** app from OS
* open demo (http://master.origin.font-loading.fgtest.com/font-events.html) in new background unactive tab (`middle mouse button click` OR `ctrl+click`)
* fast press `alt+tab` (to switch to other app, make chrome unactive)
* wait page loads
* switch to chrome back, switch to demo tab - check that page with default fonts

![anim](https://cloud.githubusercontent.com/assets/137919/6264627/0adee55a-b82e-11e4-9b41-271dc4f8c35e.gif)

Looks like script works uncorrect when **both**:
* not active chrome app
* and not active loading tab (((

It uses scroll event (described in readme) , maybe chrome doesn't fires it?

**Comment by bramstein** [comment]
Great bug report, thanks a lot!

I had a look and I think your suspicion is correct. It looks like Chrome doesn't fire scroll events when it is inactive (merely an inactive tab works fine). Firefox seems to fire scroll events just fine. If I increase the default timeout and switch back to the tab within the timeout the scroll event fires correctly.

I tried to reproduce this on OS X, but it works as expected (which isn't surprising given its different window model). I'll need to think about this for a bit (cc @zachleat & @scottjehl).

**Comment by Dechowmedia** [comment]
Would perhaps firing a scroll event manually at 0 (or 1) pixels from current scroll position when the script is loaded, work as a workaround perhaps?

**Comment by bramstein** [comment]
Would that trick Chrome into firing scroll events for inactive windows? I was thinking about either removing the timeout (with the downside that if font loading fails it leaves test spans in the DOM) or replacing the `setTimeout` with `requestAnimationFrame` so the "timeout" would get throttled until the tab becomes active again.

**Comment by Dechowmedia** [comment]
It's either that or try to see if the function works if you run it on a window blur/focus

http://stackoverflow.com/questions/1760250/how-to-tell-if-browser-tab-is-active

**Comment by kompot** [comment]
I can reproduce this on OS X in Chrome 41.

1. Open page with correctly resolved FontFaceObserver promises.
2. Open new tab of the same site (with same font promises) in background.
3. Wait for timeout to happen (do not switch to new tab)
4. Promise is rejected.

**Comment by bramstein** [comment]
Thanks for the reproduction. The problem is that the JavaScript event queue does not run in active tabs, but the setTimeout I use for detecting font load timeouts. So when you switch back to an inactive tab the promise has already been rejected. The scroll events are still sent though.

I think this is a big problem caused by using scroll events. There are two ways we can try to fix this:

1. Use a timeout method that is also paused in inactive tabs. This will make sure your promises are resolved when you switch back to the tab. The downside is that this will trigger the promise much later then expected (including any code that uses the promise).
2. Switch back to checking for font loads using a timeout. The downside is that this is much more expensive because it read `offsetWidth` every N ms.

I'm currently leaning towards 2, but any ideas are welcome.

**Comment by bramstein** [comment]
A third option could be detecting inactive tabs (using the page visibility API) and then falling back the old `setTimeout` trick. It would be slightly less efficient, but that's not a big deal for inactive tabs. It does require a second implementation.

**Comment by bramstein** [comment]
I think I fixed it. In active tab/windows FontFaceObserver will use the scroll event method and in inactive tabs (and older browsers) it will use the same polling method as used in the Web Font Loader. Please give v1.4.4 a try and let me know if that fixes the issue for you.

**Comment by bramstein** [comment]
I haven't heard back on this, so I'm assuming it is fixed now. Please feel free to re-open this issue if it is not the case and thanks a lot for the detailed bug report.
