### ISSUE TITLE
Use insertBefore instead of appendChild

### ISSUE THREAD

**Issue by rarkins** [bramstein/fontfaceobserver#10]
Since adding this script (per @scottjehl's recommendation) I found some misbehaving IE clients making my client-side JS error count go through the roof.

I'm no expert, but I think insertBefore is still recommended over appendChild? http://www.paulirish.com/2011/surefire-dom-element-insertion/

**Comment by bramstein** [comment]
I'm not against changing it, but I'd like to understand the problem better. What kind of errors are you seeing?

**Comment by scottjehl** [comment]
The typical issue was in older versions of IE, where attempting to appendChild to an element that had not yet fully loaded (all of its child nodes) would cause an error.

I agree - insertBefore with the first script tag in the head is often the safest alternative.

**Comment by bramstein** [comment]
@rarkins Do you have some examples of exceptions?

**Comment by rarkins** [comment]
@bramstein in my error checking, these were getting logged as simply `Cannot read property 'appendChild' of null`

**Comment by bramstein** [comment]
Thanks! That looks like it might be related to trying to append to `document.body` before the body is available. How do you embed fontfaceobserver? Do you have a demo page somewhere?

**Comment by rarkins** [comment]
@bramstein as mentioned in #11 I unfortunately had to revert this feature for an unrelated problem, so I don't have any demo page. I plan to try again in future though.

This `appendChild` problem only occurred on old IE though, from what I could tell - not on any modern browsers. I was loading fontfaceobserver using webpack, and had made it essentially the first thing that webpack loaded (as I think getting the font updated is more important than other JS). We have a lot of third party code that's loaded in the same way (analytics packages, Swiftype search, svg4everybody, etc) and this was the only library triggering client side errors. 

Is there any technical advantage to fontfaceobserver in perservering with appendChild versus just using insertBefore? I thought they were essentially equivalent so no reason not to switch.

**Comment by bramstein** [comment]
@rarkins The reason I'm asking is because I can't reproduce this issue (tested IE6-8). On these browsers the promise is rejected (which seems like sensible behaviour to me). I'd like to have a test case before I make any changes to the code so I'm sure it'll fix the problem.

Did you place FontFaceObserver in `head`?

**Comment by rarkins** [comment]
Fontfaceobserver was called from a JS file which was loaded asynchronously from within the head.

**Comment by bramstein** [comment]
Sorry for the late response. I had another look at this problem and I don't think it is caused by old Internet Explorer versions. The error messages in Internet Explorer are different. These look like the messages generated by Chrome.

I think this error is caused by including FontFaceObserver in the head, while it depends on the body being available. This sometimes works because of timing, but it can also fail. I could write some code for the observer to wait until the body element is available or we could document that FontFaceObserver should not be called until the `body` element is available. I'm not sure what is preferable: detection adds extra code and documentation can be glossed over.

Out of curiosity, why do you place FontFaceObserver in the `head`?

**Comment by rarkins** [comment]
I have a single, asynchronous JS include in the `<head>` that kicks off everything required on the page. These range from every embedded/built library we might use on client side (bootstrap, leaflet, d3, etc) to also third party runtime includes like Google Analytics. I haven't seen any have problems with this approach before.

Also, out of all that JS, "Loading fonts for the user" would rate pretty high on my page priorities, right after the library I use to catch such JS failures. So if given a choice I'd still want anything in the font critical path to be in the head anyway.

**Comment by bramstein** [comment]
I gave this some more thought, and I'll add some code that waits until `document.body` is available. I agree that this is something that should just work out of the box.

**Comment by bramstein** [comment]
I've released v1.4.5 with the code for waiting for the `body` element to be available. Give it a try and see if it resolves your problem.

**Comment by bramstein** [comment]
I assume this problem has been fixed. Thanks a lot for reporting it and please feel free to re-open this issue if the problem still happens.
