### ISSUE TITLE
 commonjs export in dist file?

### ISSUE THREAD

**Issue by scottjehl** [bramstein/fontfaceobserver#37]
Love this script. 

I'm in the process of moving our [Enhance](https://github.com/filamentgroup/enhance) boilerplate to use a more automated build that pulls in its dependencies from NPM, and this script is one of the four or so dependencies I'll be referencing. Unfortunately, the NPM distribution doesn't appear to have a commonjs module export, but I may have missed something.  If not, would that be something worth adding?

Maybe something like this would work?

```
// commonjs
if( typeof module !== "undefined" ){
	module.exports = FontFaceObserver;
}
```

**Comment by kennethormandy** [comment]
Hey @scottjehl! We were just discussing that in https://github.com/bramstein/fontfaceobserver/pull/29, not that easy to find since it was already merged, sorry about that.

So you should already be able to do this:

```js
require('fontfaceobserver')

// Everything else as normal
var observer = new FontFaceObserver('Moriston', {
  weight: 800
})
```

…but I was thinking of opening up a PR that did the more expected CommonJS, similar to your example.

**Comment by bramstein** [comment]
Great idea. This is now in v1.6.1, I've added an example to the README. Thanks!
