### ISSUE TITLE
Material Icons font in Safari OS X: issue and fix

### ISSUE THREAD

**Issue by dchest** [bramstein/fontfaceobserver#52]
Material Icons is a font that uses ligatures to display icons (http://google.github.io/material-design-icons/#icon-font-for-the-web).

Both Chrome and Firefox successfully detect when it's loaded, but on Safari 9.0.3 (OS X 10.11.3, Retina display) checking for it fails (even though the font is actually loaded).

Test case:

```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <link href='https://fonts.googleapis.com/css?family=Material+Icons|Source+Sans+Pro' rel='stylesheet' type='text/css'>
  </head>
  <body>
<i class="material-icons">favorite</i>
<div id="result">Checking...</div>
<script src="https://rawgit.com/bramstein/fontfaceobserver/master/fontfaceobserver.js"></script>
<script>
var fontObservers = [
    new FontFaceObserver('Material Icons'),
    new FontFaceObserver('Source Sans Pro')
];
var resultElm = document.getElementById('result');

Promise.all(fontObservers.map(function(observer) {
    return observer.check(null, 5000);
})).then(function() {
  resultElm.innerText = 'OK';
}).catch(function() {
  resultElm.innerText = 'Failed to load';
});
</script>
</body>
```

To fix the issue, I used text that triggers ligature:

```javascript
observer.check('favorite', 5000);
```

However default text plus ligature (`'BESbswy favorite'`) doesn't work. The question is: why Chrome and FF don't have problems with it, and can this be somehow fixed in FontFaceObserver itself?

Thank you!

**Comment by bramstein** [comment]
@dchest Font Face Observer uses the native font loading API on Chrome and Firefox, so it is likely that it has more internal information about what is loaded and what is not. As for why `BESbswy favorite` doesn't work; it looks like the Material Icons font is poorly implemented when normal text and icon "ligatures" are mixed. I would recommend only including the ligature as the test string for the icon font, and leaving the test string for Source Sans Pro as default.

I don't think this issue can be fixed in Font Face Observer, it'll require some modifications in the font itself.

**Comment by dchest** [comment]
I see, thank you!
