### ISSUE TITLE
On slowest throttle (GPRS) Uncaught error in Promise

### ISSUE THREAD

**Issue by peterdillon** [bramstein/fontfaceobserver#71]
https://codepen.io/peterdillon/pen/kXvZjd

![image](https://cloud.githubusercontent.com/assets/307229/16876688/e158e7f2-4a72-11e6-98d3-6428ed042b06.png)

**Comment by kilianso** [comment]
I have the same problem, solved it by increasing the waiting-time, but it would be great to have a "try again" option. 

This will wait 10 seconds (instead of 3 wich is the standard behavoir)

font.load(null, 10000).then(function () {
	console.log('fonts loaded')
});

**Comment by peterdillon** [comment]
I see okay - thanks for the suggestion. This can be closed if the admin is satisfied.

**Comment by bramstein** [comment]
Extending the timeout is in this case the correct option. The timeout is set at three seconds because that's the generally accepted timeout for web fonts. In my personal opinion the browser should stop downloading web fonts if it takes longer than that.

It would be fairly simple to write a retry function, so I don't think it should be part of Font Face Observer by default.
