### ISSUE TITLE
Safari doesn't fire promises

### ISSUE THREAD

**Issue by WebDerekh** [bramstein/fontfaceobserver#95]
Already two days I've been trying to implement Zach CRITICAL FOFT preloading strategy and I've met an issue in Safari. The fonts get appears in resources, but Safari doesn't fire promises so my class magic doesn't work. The same code works fine in Chrome and Mozilla. What I do wrong?  I've attached my test case.

https://www.dropbox.com/s/0kt1wbpkc11hwp9/Archive.zip?dl=0

**Comment by miklb** [comment]
I'm having a similar problem with Safari 10.0.3 (12602.4.8) and FFO 2.0.9 

I tried changing the timeout to no avail. I'm attempting to load 2 different fonts to start
```
var fontASubset = new FontFaceObserver('SSP-Subset');
var fontBSubset = new FontFaceObserver('SCP-Subset');

Promise.all([fontASubset.load(null, 5000), fontBSubset.load(null, 5000)]).then(function () {
    document.documentElement.className += " font-initialize";
```

Works in Safari Tech Preview, Chrome, Firefox

Any suggestions greatly appreciated.

**Comment by bramstein** [comment]
Took a little while to dig into this. There are two issues:

1. Due to a bug in Safari's native font loading API Font Face Observer falls back to the old way of detecting font loads (measuring a `<span>`'s width before and after the font is applied).
2. The old font load detection code relies on a built-in string `BESbswy` to detect a font has loaded. You have created a subset without lowercase, so FFO fails to detect the font has loaded. You can pass a custom test string to Font Face Observer for these cases. For example, by using `BES` FFO correctly detects the font loads.

The following example works for me.

```js
var fontASubset = new FontFaceObserver('DIN-min');

fontASubset.load('BES').then(function () {
 console.log('font loaded');
});
```

By the way, just looking at your fonts, you probably don't need Zach's critical FOFT. You might be able to squeeze all necessary characters in your subset without having the overhead of loading two fonts. Generally I recommend against using critical FOFT because it is complex, and doesn't buy you much unless you can get the minimal font down to an incredibly small size. It's a tradeoff between the cost of an extra HTTP request (not to mention the costs of parsing a font) and a few more bytes. Usually it's more cost effective to transfer more bytes.
